// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: internal/contracts/marketplace.proto

package contracts

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MarketplaceSearchConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Query         string                 `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
	Category      string                 `protobuf:"bytes,2,opt,name=category,proto3" json:"category,omitempty"`
	Tags          []string               `protobuf:"bytes,3,rep,name=tags,proto3" json:"tags,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MarketplaceSearchConfig) Reset() {
	*x = MarketplaceSearchConfig{}
	mi := &file_internal_contracts_marketplace_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MarketplaceSearchConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MarketplaceSearchConfig) ProtoMessage() {}

func (x *MarketplaceSearchConfig) ProtoReflect() protoreflect.Message {
	mi := &file_internal_contracts_marketplace_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MarketplaceSearchConfig.ProtoReflect.Descriptor instead.
func (*MarketplaceSearchConfig) Descriptor() ([]byte, []int) {
	return file_internal_contracts_marketplace_proto_rawDescGZIP(), []int{0}
}

func (x *MarketplaceSearchConfig) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *MarketplaceSearchConfig) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *MarketplaceSearchConfig) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

type MarketplaceSearchInput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Query         string                 `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
	Category      string                 `protobuf:"bytes,2,opt,name=category,proto3" json:"category,omitempty"`
	Tags          []string               `protobuf:"bytes,3,rep,name=tags,proto3" json:"tags,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MarketplaceSearchInput) Reset() {
	*x = MarketplaceSearchInput{}
	mi := &file_internal_contracts_marketplace_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MarketplaceSearchInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MarketplaceSearchInput) ProtoMessage() {}

func (x *MarketplaceSearchInput) ProtoReflect() protoreflect.Message {
	mi := &file_internal_contracts_marketplace_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MarketplaceSearchInput.ProtoReflect.Descriptor instead.
func (*MarketplaceSearchInput) Descriptor() ([]byte, []int) {
	return file_internal_contracts_marketplace_proto_rawDescGZIP(), []int{1}
}

func (x *MarketplaceSearchInput) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *MarketplaceSearchInput) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *MarketplaceSearchInput) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

type MarketplaceDetailConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MarketplaceDetailConfig) Reset() {
	*x = MarketplaceDetailConfig{}
	mi := &file_internal_contracts_marketplace_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MarketplaceDetailConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MarketplaceDetailConfig) ProtoMessage() {}

func (x *MarketplaceDetailConfig) ProtoReflect() protoreflect.Message {
	mi := &file_internal_contracts_marketplace_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MarketplaceDetailConfig.ProtoReflect.Descriptor instead.
func (*MarketplaceDetailConfig) Descriptor() ([]byte, []int) {
	return file_internal_contracts_marketplace_proto_rawDescGZIP(), []int{2}
}

func (x *MarketplaceDetailConfig) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type MarketplaceDetailInput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MarketplaceDetailInput) Reset() {
	*x = MarketplaceDetailInput{}
	mi := &file_internal_contracts_marketplace_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MarketplaceDetailInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MarketplaceDetailInput) ProtoMessage() {}

func (x *MarketplaceDetailInput) ProtoReflect() protoreflect.Message {
	mi := &file_internal_contracts_marketplace_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MarketplaceDetailInput.ProtoReflect.Descriptor instead.
func (*MarketplaceDetailInput) Descriptor() ([]byte, []int) {
	return file_internal_contracts_marketplace_proto_rawDescGZIP(), []int{3}
}

func (x *MarketplaceDetailInput) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type MarketplaceInstallConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MarketplaceInstallConfig) Reset() {
	*x = MarketplaceInstallConfig{}
	mi := &file_internal_contracts_marketplace_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MarketplaceInstallConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MarketplaceInstallConfig) ProtoMessage() {}

func (x *MarketplaceInstallConfig) ProtoReflect() protoreflect.Message {
	mi := &file_internal_contracts_marketplace_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MarketplaceInstallConfig.ProtoReflect.Descriptor instead.
func (*MarketplaceInstallConfig) Descriptor() ([]byte, []int) {
	return file_internal_contracts_marketplace_proto_rawDescGZIP(), []int{4}
}

func (x *MarketplaceInstallConfig) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type MarketplaceInstallInput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MarketplaceInstallInput) Reset() {
	*x = MarketplaceInstallInput{}
	mi := &file_internal_contracts_marketplace_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MarketplaceInstallInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MarketplaceInstallInput) ProtoMessage() {}

func (x *MarketplaceInstallInput) ProtoReflect() protoreflect.Message {
	mi := &file_internal_contracts_marketplace_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MarketplaceInstallInput.ProtoReflect.Descriptor instead.
func (*MarketplaceInstallInput) Descriptor() ([]byte, []int) {
	return file_internal_contracts_marketplace_proto_rawDescGZIP(), []int{5}
}

func (x *MarketplaceInstallInput) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type MarketplaceInstalledConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MarketplaceInstalledConfig) Reset() {
	*x = MarketplaceInstalledConfig{}
	mi := &file_internal_contracts_marketplace_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MarketplaceInstalledConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MarketplaceInstalledConfig) ProtoMessage() {}

func (x *MarketplaceInstalledConfig) ProtoReflect() protoreflect.Message {
	mi := &file_internal_contracts_marketplace_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MarketplaceInstalledConfig.ProtoReflect.Descriptor instead.
func (*MarketplaceInstalledConfig) Descriptor() ([]byte, []int) {
	return file_internal_contracts_marketplace_proto_rawDescGZIP(), []int{6}
}

type MarketplaceInstalledInput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MarketplaceInstalledInput) Reset() {
	*x = MarketplaceInstalledInput{}
	mi := &file_internal_contracts_marketplace_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MarketplaceInstalledInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MarketplaceInstalledInput) ProtoMessage() {}

func (x *MarketplaceInstalledInput) ProtoReflect() protoreflect.Message {
	mi := &file_internal_contracts_marketplace_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MarketplaceInstalledInput.ProtoReflect.Descriptor instead.
func (*MarketplaceInstalledInput) Descriptor() ([]byte, []int) {
	return file_internal_contracts_marketplace_proto_rawDescGZIP(), []int{7}
}

type MarketplaceUninstallConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MarketplaceUninstallConfig) Reset() {
	*x = MarketplaceUninstallConfig{}
	mi := &file_internal_contracts_marketplace_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MarketplaceUninstallConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MarketplaceUninstallConfig) ProtoMessage() {}

func (x *MarketplaceUninstallConfig) ProtoReflect() protoreflect.Message {
	mi := &file_internal_contracts_marketplace_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MarketplaceUninstallConfig.ProtoReflect.Descriptor instead.
func (*MarketplaceUninstallConfig) Descriptor() ([]byte, []int) {
	return file_internal_contracts_marketplace_proto_rawDescGZIP(), []int{8}
}

func (x *MarketplaceUninstallConfig) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type MarketplaceUninstallInput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MarketplaceUninstallInput) Reset() {
	*x = MarketplaceUninstallInput{}
	mi := &file_internal_contracts_marketplace_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MarketplaceUninstallInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MarketplaceUninstallInput) ProtoMessage() {}

func (x *MarketplaceUninstallInput) ProtoReflect() protoreflect.Message {
	mi := &file_internal_contracts_marketplace_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MarketplaceUninstallInput.ProtoReflect.Descriptor instead.
func (*MarketplaceUninstallInput) Descriptor() ([]byte, []int) {
	return file_internal_contracts_marketplace_proto_rawDescGZIP(), []int{9}
}

func (x *MarketplaceUninstallInput) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type MarketplaceUpdateConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MarketplaceUpdateConfig) Reset() {
	*x = MarketplaceUpdateConfig{}
	mi := &file_internal_contracts_marketplace_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MarketplaceUpdateConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MarketplaceUpdateConfig) ProtoMessage() {}

func (x *MarketplaceUpdateConfig) ProtoReflect() protoreflect.Message {
	mi := &file_internal_contracts_marketplace_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MarketplaceUpdateConfig.ProtoReflect.Descriptor instead.
func (*MarketplaceUpdateConfig) Descriptor() ([]byte, []int) {
	return file_internal_contracts_marketplace_proto_rawDescGZIP(), []int{10}
}

func (x *MarketplaceUpdateConfig) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type MarketplaceUpdateInput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MarketplaceUpdateInput) Reset() {
	*x = MarketplaceUpdateInput{}
	mi := &file_internal_contracts_marketplace_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MarketplaceUpdateInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MarketplaceUpdateInput) ProtoMessage() {}

func (x *MarketplaceUpdateInput) ProtoReflect() protoreflect.Message {
	mi := &file_internal_contracts_marketplace_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MarketplaceUpdateInput.ProtoReflect.Descriptor instead.
func (*MarketplaceUpdateInput) Descriptor() ([]byte, []int) {
	return file_internal_contracts_marketplace_proto_rawDescGZIP(), []int{11}
}

func (x *MarketplaceUpdateInput) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type MarketplacePlugin struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Version       string                 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Author        string                 `protobuf:"bytes,4,opt,name=author,proto3" json:"author,omitempty"`
	Category      string                 `protobuf:"bytes,5,opt,name=category,proto3" json:"category,omitempty"`
	Tags          []string               `protobuf:"bytes,6,rep,name=tags,proto3" json:"tags,omitempty"`
	Downloads     int32                  `protobuf:"varint,7,opt,name=downloads,proto3" json:"downloads,omitempty"`
	Rating        float64                `protobuf:"fixed64,8,opt,name=rating,proto3" json:"rating,omitempty"`
	Installed     bool                   `protobuf:"varint,9,opt,name=installed,proto3" json:"installed,omitempty"`
	InstalledAt   string                 `protobuf:"bytes,10,opt,name=installed_at,json=installedAt,proto3" json:"installed_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MarketplacePlugin) Reset() {
	*x = MarketplacePlugin{}
	mi := &file_internal_contracts_marketplace_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MarketplacePlugin) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MarketplacePlugin) ProtoMessage() {}

func (x *MarketplacePlugin) ProtoReflect() protoreflect.Message {
	mi := &file_internal_contracts_marketplace_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MarketplacePlugin.ProtoReflect.Descriptor instead.
func (*MarketplacePlugin) Descriptor() ([]byte, []int) {
	return file_internal_contracts_marketplace_proto_rawDescGZIP(), []int{12}
}

func (x *MarketplacePlugin) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *MarketplacePlugin) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *MarketplacePlugin) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *MarketplacePlugin) GetAuthor() string {
	if x != nil {
		return x.Author
	}
	return ""
}

func (x *MarketplacePlugin) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *MarketplacePlugin) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *MarketplacePlugin) GetDownloads() int32 {
	if x != nil {
		return x.Downloads
	}
	return 0
}

func (x *MarketplacePlugin) GetRating() float64 {
	if x != nil {
		return x.Rating
	}
	return 0
}

func (x *MarketplacePlugin) GetInstalled() bool {
	if x != nil {
		return x.Installed
	}
	return false
}

func (x *MarketplacePlugin) GetInstalledAt() string {
	if x != nil {
		return x.InstalledAt
	}
	return ""
}

type MarketplaceSearchOutput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Results       []*MarketplacePlugin   `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty"`
	Count         int32                  `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	Error         string                 `protobuf:"bytes,100,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MarketplaceSearchOutput) Reset() {
	*x = MarketplaceSearchOutput{}
	mi := &file_internal_contracts_marketplace_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MarketplaceSearchOutput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MarketplaceSearchOutput) ProtoMessage() {}

func (x *MarketplaceSearchOutput) ProtoReflect() protoreflect.Message {
	mi := &file_internal_contracts_marketplace_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MarketplaceSearchOutput.ProtoReflect.Descriptor instead.
func (*MarketplaceSearchOutput) Descriptor() ([]byte, []int) {
	return file_internal_contracts_marketplace_proto_rawDescGZIP(), []int{13}
}

func (x *MarketplaceSearchOutput) GetResults() []*MarketplacePlugin {
	if x != nil {
		return x.Results
	}
	return nil
}

func (x *MarketplaceSearchOutput) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *MarketplaceSearchOutput) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type MarketplaceDetailOutput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Plugin        *MarketplacePlugin     `protobuf:"bytes,1,opt,name=plugin,proto3" json:"plugin,omitempty"`
	Error         string                 `protobuf:"bytes,100,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MarketplaceDetailOutput) Reset() {
	*x = MarketplaceDetailOutput{}
	mi := &file_internal_contracts_marketplace_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MarketplaceDetailOutput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MarketplaceDetailOutput) ProtoMessage() {}

func (x *MarketplaceDetailOutput) ProtoReflect() protoreflect.Message {
	mi := &file_internal_contracts_marketplace_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MarketplaceDetailOutput.ProtoReflect.Descriptor instead.
func (*MarketplaceDetailOutput) Descriptor() ([]byte, []int) {
	return file_internal_contracts_marketplace_proto_rawDescGZIP(), []int{14}
}

func (x *MarketplaceDetailOutput) GetPlugin() *MarketplacePlugin {
	if x != nil {
		return x.Plugin
	}
	return nil
}

func (x *MarketplaceDetailOutput) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type MarketplaceInstallOutput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Installed     bool                   `protobuf:"varint,1,opt,name=installed,proto3" json:"installed,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Error         string                 `protobuf:"bytes,100,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MarketplaceInstallOutput) Reset() {
	*x = MarketplaceInstallOutput{}
	mi := &file_internal_contracts_marketplace_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MarketplaceInstallOutput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MarketplaceInstallOutput) ProtoMessage() {}

func (x *MarketplaceInstallOutput) ProtoReflect() protoreflect.Message {
	mi := &file_internal_contracts_marketplace_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MarketplaceInstallOutput.ProtoReflect.Descriptor instead.
func (*MarketplaceInstallOutput) Descriptor() ([]byte, []int) {
	return file_internal_contracts_marketplace_proto_rawDescGZIP(), []int{15}
}

func (x *MarketplaceInstallOutput) GetInstalled() bool {
	if x != nil {
		return x.Installed
	}
	return false
}

func (x *MarketplaceInstallOutput) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *MarketplaceInstallOutput) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type MarketplaceInstalledOutput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Plugins       []*MarketplacePlugin   `protobuf:"bytes,1,rep,name=plugins,proto3" json:"plugins,omitempty"`
	Count         int32                  `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	Error         string                 `protobuf:"bytes,100,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MarketplaceInstalledOutput) Reset() {
	*x = MarketplaceInstalledOutput{}
	mi := &file_internal_contracts_marketplace_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MarketplaceInstalledOutput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MarketplaceInstalledOutput) ProtoMessage() {}

func (x *MarketplaceInstalledOutput) ProtoReflect() protoreflect.Message {
	mi := &file_internal_contracts_marketplace_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MarketplaceInstalledOutput.ProtoReflect.Descriptor instead.
func (*MarketplaceInstalledOutput) Descriptor() ([]byte, []int) {
	return file_internal_contracts_marketplace_proto_rawDescGZIP(), []int{16}
}

func (x *MarketplaceInstalledOutput) GetPlugins() []*MarketplacePlugin {
	if x != nil {
		return x.Plugins
	}
	return nil
}

func (x *MarketplaceInstalledOutput) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *MarketplaceInstalledOutput) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type MarketplaceUninstallOutput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uninstalled   bool                   `protobuf:"varint,1,opt,name=uninstalled,proto3" json:"uninstalled,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Error         string                 `protobuf:"bytes,100,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MarketplaceUninstallOutput) Reset() {
	*x = MarketplaceUninstallOutput{}
	mi := &file_internal_contracts_marketplace_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MarketplaceUninstallOutput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MarketplaceUninstallOutput) ProtoMessage() {}

func (x *MarketplaceUninstallOutput) ProtoReflect() protoreflect.Message {
	mi := &file_internal_contracts_marketplace_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MarketplaceUninstallOutput.ProtoReflect.Descriptor instead.
func (*MarketplaceUninstallOutput) Descriptor() ([]byte, []int) {
	return file_internal_contracts_marketplace_proto_rawDescGZIP(), []int{17}
}

func (x *MarketplaceUninstallOutput) GetUninstalled() bool {
	if x != nil {
		return x.Uninstalled
	}
	return false
}

func (x *MarketplaceUninstallOutput) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *MarketplaceUninstallOutput) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type MarketplaceUpdateOutput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Updated       bool                   `protobuf:"varint,1,opt,name=updated,proto3" json:"updated,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Error         string                 `protobuf:"bytes,100,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MarketplaceUpdateOutput) Reset() {
	*x = MarketplaceUpdateOutput{}
	mi := &file_internal_contracts_marketplace_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MarketplaceUpdateOutput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MarketplaceUpdateOutput) ProtoMessage() {}

func (x *MarketplaceUpdateOutput) ProtoReflect() protoreflect.Message {
	mi := &file_internal_contracts_marketplace_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MarketplaceUpdateOutput.ProtoReflect.Descriptor instead.
func (*MarketplaceUpdateOutput) Descriptor() ([]byte, []int) {
	return file_internal_contracts_marketplace_proto_rawDescGZIP(), []int{18}
}

func (x *MarketplaceUpdateOutput) GetUpdated() bool {
	if x != nil {
		return x.Updated
	}
	return false
}

func (x *MarketplaceUpdateOutput) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *MarketplaceUpdateOutput) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

var File_internal_contracts_marketplace_proto protoreflect.FileDescriptor

const file_internal_contracts_marketplace_proto_rawDesc = "" +
	"\n" +
	"$internal/contracts/marketplace.proto\x12\x1fworkflow.plugins.marketplace.v1\"_\n" +
	"\x17MarketplaceSearchConfig\x12\x14\n" +
	"\x05query\x18\x01 \x01(\tR\x05query\x12\x1a\n" +
	"\bcategory\x18\x02 \x01(\tR\bcategory\x12\x12\n" +
	"\x04tags\x18\x03 \x03(\tR\x04tags\"^\n" +
	"\x16MarketplaceSearchInput\x12\x14\n" +
	"\x05query\x18\x01 \x01(\tR\x05query\x12\x1a\n" +
	"\bcategory\x18\x02 \x01(\tR\bcategory\x12\x12\n" +
	"\x04tags\x18\x03 \x03(\tR\x04tags\"-\n" +
	"\x17MarketplaceDetailConfig\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\",\n" +
	"\x16MarketplaceDetailInput\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\".\n" +
	"\x18MarketplaceInstallConfig\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"-\n" +
	"\x17MarketplaceInstallInput\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"\x1c\n" +
	"\x1aMarketplaceInstalledConfig\"\x1b\n" +
	"\x19MarketplaceInstalledInput\"0\n" +
	"\x1aMarketplaceUninstallConfig\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"/\n" +
	"\x19MarketplaceUninstallInput\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"-\n" +
	"\x17MarketplaceUpdateConfig\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\",\n" +
	"\x16MarketplaceUpdateInput\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"\xa2\x02\n" +
	"\x11MarketplacePlugin\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x16\n" +
	"\x06author\x18\x04 \x01(\tR\x06author\x12\x1a\n" +
	"\bcategory\x18\x05 \x01(\tR\bcategory\x12\x12\n" +
	"\x04tags\x18\x06 \x03(\tR\x04tags\x12\x1c\n" +
	"\tdownloads\x18\a \x01(\x05R\tdownloads\x12\x16\n" +
	"\x06rating\x18\b \x01(\x01R\x06rating\x12\x1c\n" +
	"\tinstalled\x18\t \x01(\bR\tinstalled\x12!\n" +
	"\finstalled_at\x18\n" +
	" \x01(\tR\vinstalledAt\"\x93\x01\n" +
	"\x17MarketplaceSearchOutput\x12L\n" +
	"\aresults\x18\x01 \x03(\v22.workflow.plugins.marketplace.v1.MarketplacePluginR\aresults\x12\x14\n" +
	"\x05count\x18\x02 \x01(\x05R\x05count\x12\x14\n" +
	"\x05error\x18d \x01(\tR\x05error\"{\n" +
	"\x17MarketplaceDetailOutput\x12J\n" +
	"\x06plugin\x18\x01 \x01(\v22.workflow.plugins.marketplace.v1.MarketplacePluginR\x06plugin\x12\x14\n" +
	"\x05error\x18d \x01(\tR\x05error\"b\n" +
	"\x18MarketplaceInstallOutput\x12\x1c\n" +
	"\tinstalled\x18\x01 \x01(\bR\tinstalled\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x14\n" +
	"\x05error\x18d \x01(\tR\x05error\"\x96\x01\n" +
	"\x1aMarketplaceInstalledOutput\x12L\n" +
	"\aplugins\x18\x01 \x03(\v22.workflow.plugins.marketplace.v1.MarketplacePluginR\aplugins\x12\x14\n" +
	"\x05count\x18\x02 \x01(\x05R\x05count\x12\x14\n" +
	"\x05error\x18d \x01(\tR\x05error\"h\n" +
	"\x1aMarketplaceUninstallOutput\x12 \n" +
	"\vuninstalled\x18\x01 \x01(\bR\vuninstalled\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x14\n" +
	"\x05error\x18d \x01(\tR\x05error\"]\n" +
	"\x17MarketplaceUpdateOutput\x12\x18\n" +
	"\aupdated\x18\x01 \x01(\bR\aupdated\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x14\n" +
	"\x05error\x18d \x01(\tR\x05errorBGZEgithub.com/GoCodeAlone/workflow-plugin-marketplace/internal/contractsb\x06proto3"

var (
	file_internal_contracts_marketplace_proto_rawDescOnce sync.Once
	file_internal_contracts_marketplace_proto_rawDescData []byte
)

func file_internal_contracts_marketplace_proto_rawDescGZIP() []byte {
	file_internal_contracts_marketplace_proto_rawDescOnce.Do(func() {
		file_internal_contracts_marketplace_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_contracts_marketplace_proto_rawDesc), len(file_internal_contracts_marketplace_proto_rawDesc)))
	})
	return file_internal_contracts_marketplace_proto_rawDescData
}

var file_internal_contracts_marketplace_proto_msgTypes = make([]protoimpl.MessageInfo, 19)
var file_internal_contracts_marketplace_proto_goTypes = []any{
	(*MarketplaceSearchConfig)(nil),    // 0: workflow.plugins.marketplace.v1.MarketplaceSearchConfig
	(*MarketplaceSearchInput)(nil),     // 1: workflow.plugins.marketplace.v1.MarketplaceSearchInput
	(*MarketplaceDetailConfig)(nil),    // 2: workflow.plugins.marketplace.v1.MarketplaceDetailConfig
	(*MarketplaceDetailInput)(nil),     // 3: workflow.plugins.marketplace.v1.MarketplaceDetailInput
	(*MarketplaceInstallConfig)(nil),   // 4: workflow.plugins.marketplace.v1.MarketplaceInstallConfig
	(*MarketplaceInstallInput)(nil),    // 5: workflow.plugins.marketplace.v1.MarketplaceInstallInput
	(*MarketplaceInstalledConfig)(nil), // 6: workflow.plugins.marketplace.v1.MarketplaceInstalledConfig
	(*MarketplaceInstalledInput)(nil),  // 7: workflow.plugins.marketplace.v1.MarketplaceInstalledInput
	(*MarketplaceUninstallConfig)(nil), // 8: workflow.plugins.marketplace.v1.MarketplaceUninstallConfig
	(*MarketplaceUninstallInput)(nil),  // 9: workflow.plugins.marketplace.v1.MarketplaceUninstallInput
	(*MarketplaceUpdateConfig)(nil),    // 10: workflow.plugins.marketplace.v1.MarketplaceUpdateConfig
	(*MarketplaceUpdateInput)(nil),     // 11: workflow.plugins.marketplace.v1.MarketplaceUpdateInput
	(*MarketplacePlugin)(nil),          // 12: workflow.plugins.marketplace.v1.MarketplacePlugin
	(*MarketplaceSearchOutput)(nil),    // 13: workflow.plugins.marketplace.v1.MarketplaceSearchOutput
	(*MarketplaceDetailOutput)(nil),    // 14: workflow.plugins.marketplace.v1.MarketplaceDetailOutput
	(*MarketplaceInstallOutput)(nil),   // 15: workflow.plugins.marketplace.v1.MarketplaceInstallOutput
	(*MarketplaceInstalledOutput)(nil), // 16: workflow.plugins.marketplace.v1.MarketplaceInstalledOutput
	(*MarketplaceUninstallOutput)(nil), // 17: workflow.plugins.marketplace.v1.MarketplaceUninstallOutput
	(*MarketplaceUpdateOutput)(nil),    // 18: workflow.plugins.marketplace.v1.MarketplaceUpdateOutput
}
var file_internal_contracts_marketplace_proto_depIdxs = []int32{
	12, // 0: workflow.plugins.marketplace.v1.MarketplaceSearchOutput.results:type_name -> workflow.plugins.marketplace.v1.MarketplacePlugin
	12, // 1: workflow.plugins.marketplace.v1.MarketplaceDetailOutput.plugin:type_name -> workflow.plugins.marketplace.v1.MarketplacePlugin
	12, // 2: workflow.plugins.marketplace.v1.MarketplaceInstalledOutput.plugins:type_name -> workflow.plugins.marketplace.v1.MarketplacePlugin
	3,  // [3:3] is the sub-list for method output_type
	3,  // [3:3] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_internal_contracts_marketplace_proto_init() }
func file_internal_contracts_marketplace_proto_init() {
	if File_internal_contracts_marketplace_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_contracts_marketplace_proto_rawDesc), len(file_internal_contracts_marketplace_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   19,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_internal_contracts_marketplace_proto_goTypes,
		DependencyIndexes: file_internal_contracts_marketplace_proto_depIdxs,
		MessageInfos:      file_internal_contracts_marketplace_proto_msgTypes,
	}.Build()
	File_internal_contracts_marketplace_proto = out.File
	file_internal_contracts_marketplace_proto_goTypes = nil
	file_internal_contracts_marketplace_proto_depIdxs = nil
}
